# Generated by Django 5.1.3 on 2024-11-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="List",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("task", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("due_date", models.DateField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("High", "High"),
                            ("Medium", "Medium"),
                            ("Low", "Low"),
                        ],
                        default="Medium",
                        max_length=6,
                    ),
                ),
            ],
        ),
    ]
